<a href="https://colab.research.google.com/github/akashravichandran/jovian-zerotogan/blob/master/01_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# JovianML - ZerotoGAN - Assignment 1

### Some useful methods from Pytorch tensor class

Here I will be discussing some of the useful pytorch methods that will be useful for your datascience projects.
- torch.add
- torch.cat
- apply_
- torch.abs
- torch.arange

In [0]:
# Import torch and other required modules
import torch

**torch.tensor() always copies data. If you have a Tensor data and just want to change its requires_grad flag, use requires_grad_() or detach() to avoid a copy. If you have a numpy array and want to avoid a copy, use torch.as_tensor().**



## Function 1 - torch.add

Add a scalar or tensor to self tensor. If both alpha and other are specified, each element of other is scaled by alpha before being used.

When other is a tensor, the shape of other must be broadcastable with the shape of the underlying tensor



In [21]:
# Example 1 - working 
a = torch.ones(1)
b = torch.ones(1)
torch.add(a, b)

tensor([2.])

Explanation about example

In [22]:
# Example 2 - working
a = torch.randn(4)
b = torch.randn(4)
torch.add(a, b)

tensor([-0.0584,  1.8820, -0.0978,  1.1470])

Explanation about example

In [23]:
# Example 3 - breaking (to illustrate when it breaks)
# Example 1 - working (change this)
a = torch.randn(4)
b = torch.randn(2)
torch.add(a, b)

RuntimeError: ignored

Explanation about example

- The first example adds a one dimensional tensor and returns the answer as a one dimensional tensor
- The second example adds a one dimensional four elements to another one dimensional four elements tensor and returns the answer as a four element tensor.
- The third example when the dimension of the operating tensor vary, they throw a runtime error

## Function 2 - torch.cat

Concatenates the given sequence of seq tensors in the given dimension. All tensors must either have the same shape (except in the concatenating dimension) or be empty.

In [24]:
# Example 1 - working
x = torch.randn(1, 2)
torch.cat((x, x), 0)

tensor([[-0.2554, -0.1760],
        [-0.2554, -0.1760]])

Explanation about example

In [25]:
# Example 2 - working
x = torch.randn(1, 2)
torch.cat((x, x), 1)

tensor([[-0.8917,  0.3384, -0.8917,  0.3384]])

Explanation about example

In [14]:
# Example 3 - breaking (to illustrate when it breaks)
x = torch.randn(1, 2)
y = torch.randn(2, 2)
torch.cat((x, y), 1)

RuntimeError: ignored

Explanation about example

- The first example concatenates the elements of the tensor by appending to the vertical dimension
- The second example concatenates the elements of the tensor by appending to the horizontal dimension
- The third example breaks when applied to tensors of varying sizes.




```
# This is formatted as code
```

## Function 3 - apply_(callable) → Tensor

Applies the function callable to each element in the tensor, replacing each element with the value returned by callable.

In [11]:
# Example 1 - working
def square(x):
  return x * x
a = 2 * torch.ones(1, 2)
a.apply_(square)

tensor([[4., 4.]])

Explanation about example

In [26]:
# Example 2 - working
def cube(x):
  return x * x * x
a = 2 * torch.ones(1, 2)
a.apply_(cube)

tensor([[8., 8.]])

Explanation about example

In [12]:
# Example 3 - breaking (to illustrate when it breaks)
def square(x):
  return x * x
cuda0 = torch.device('cuda:0')
a = torch.ones([1, 2], dtype=torch.float64, device=cuda0)
a.apply_(square)

TypeError: ignored

Explanation about example

- The first example applies the square function to the elements of the tensor
- The second example applies the cube function to the tensor at hand
- The third example breaks when applied to the tensor of devicetype gpu, because of its incompatibility.

## Function 4 - torch.abs

Computes the element-wise absolute value of the given input tensor.

In [35]:
# Example 1 - working
torch.abs(torch.tensor(-3))


tensor(3)

Explanation about example

In [30]:
# Example 2 - working
torch.abs(torch.tensor([-1, -2, 3]))

tensor([1, 2, 3])

Explanation about example

In [34]:
# Example 3 - breaking (to illustrate when it breaks)
torch.abs(torch.tensor([True, True, False]))

RuntimeError: ignored

Explanation about example

- The first example applies the abs function to a scalar tensor
- The second example applies the abs function to a one dimensional tensor
- The third example breaks when abs is applied to boolean.

## Function 5 - torch.arange




In [37]:
# Example 1 - working
torch.arange(1, 2.5)

tensor([1., 2.])

Explanation about example

In [38]:
# Example 2 - working
torch.arange(1, 2.5, 0.5)

tensor([1.0000, 1.5000, 2.0000])

Explanation about example

In [20]:
# Example 3 - breaking (to illustrate when it breaks)
torch.arange(1, 2.5, 0)

RuntimeError: ignored

Explanation about example

- The first example gets a range of values without step specified
- The second example gets a range of values with step specified
- The third example breaks when step value is set to zero

## Conclusion

Here I have randomly picked some methods from pytorch, pytorch is really vast and it is still growing. Hope you like the methods that I have taken here to be explained. Thank you!

## Reference Links
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html

In [39]:
!pip install jovian --upgrade --quiet

     |████████████████████████████████| 92kB 4.7MB/s 


In [0]:
import jovian

In [41]:
jovian.commit()

[jovian] Error: Failed to detect Jupyter notebook or Python script. Skipping..
